services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    depends_on:
      - chat_service
      - web_app
      - user_service
      - blog_service
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"

    ports:
      - "3000:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_net

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: INFO
    ports:
      - "8082:8080"
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./paw_connect.json:/tmp/paw_connect.json
    networks:
      - traefik_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - traefik_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - traefik_net

  web_app:
    image: web_app:latest
    container_name: web_app
    ports:
      - "3005:80" # Frontend available at http://localhost:3000
    volumes:
      - ../web-app:/app
      - node_modules:/app/node_modules
    environment:
      ENV_VAR_REACT_APP_CHAT_SERVICE_URL: http://localhost:3000
      ENV_VAR_KEYCLOAK_URL: http://localhost:8082/realms/paw_connect
      ENV_VAR_KEYCLOAK_CLIENT_ID: web-app
      CHOKIDAR_USEPOLLING: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_app.rule=Host(`localhost`)"
      - "traefik.http.routers.web_app.entrypoints=web"
      - "traefik.http.routers.web_app.priority=3"

    networks:
      - traefik_net

  chat_service:
    image: chat_service:latest
    volumes:
      - ../chat_api:/app
    container_name: chat_service
    ports:
      - "8002:8000"
    depends_on:
      - redis
      - chat_db
      - elasticsearch
      - keycloak
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@chat_db:5432/chat_db
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KEYCLOAK_SERVER_URL=http://keycloak:8080 # or your internal URL if needed
      - KEYCLOAK_REALM=paw_connect
      - KEYCLOAK_ADMIN_CLIENT_SECRET=gt1mPvzJ3MVkyfs4RfaH6pJx8z1hpbKJ
      - KEYCLOAK_CLIENT_ID=chat-service
      - KEYCLOAK_CLIENT_SECRET=0T6BYixnHhjEdiv8vnMMKJDiiIqM5IJu
      - KEYCLOAK_CALLBACK_URI=http://localhost:3000/
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat_service.rule=PathPrefix(`/ws/chat`)"
      - "traefik.http.routers.chat_service.entrypoints=web"
      - "traefik.http.routers.chat_api.rule=PathPrefix(`/api/chat`)"
      - "traefik.http.routers.chat_api.entrypoints=web"
      - "traefik.http.routers.chat_service.priority=5"
      - "traefik.http.routers.chat_api.priority=5"
    networks:
      - traefik_net
    command:
      - "sh"
      - "-c"
      # - 'mkdir alembic/versions && alembic revision --autogenerate -m "Init"'
      - "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  chat_db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data_chat_db:/var/lib/postgresql/data
    networks:
      - traefik_net

  redis:
    image: "redis:latest"
    container_name: redis_chat
    ports:
      - "6379:6379"
    networks:
      - traefik_net

  user_service:
    image: user_service:latest
    volumes:
      - ../user_api:/app
    container_name: user_service
    ports:
      - "8003:8000"
    depends_on:
      - user_db
      - elasticsearch
      - keycloak
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@user_db:5432/user_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=paw_connect
      - KEYCLOAK_ADMIN_CLIENT_SECRET=wSVxDu1FL5SIbdDlqEpr9wohnB8bxYO7
      - KEYCLOAK_CLIENT_ID=chat-service
      - KEYCLOAK_CLIENT_SECRET=0T6BYixnHhjEdiv8vnMMKJDiiIqM5IJu
      - KEYCLOAK_CALLBACK_URI=http://localhost:3000/
      - KEYCLOAK_CLIIENT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3V7fKMuAO055R158iL18lehMdjFOZr1P7tmvrbQK3v/9hgbB6ROhOAmT1Aj+ml7rNMb+eMeJEPvDuE5sQm9hMUAU88bWC/pqWyCIegEEWEixeItUrBZLxEsmWagF5wFc90juNxu0qXEf2r/oKuRSdWuJXRx4IRkZm24XzlTLI/z7DZUvRL3t4e/XpnLgb8dVRw/xSmrqAFnbXbRaESDpp77KhTKlhxkVBiT5rBKRwAwI3a7kEYEFtvX3wpRimGPOh/uogtbHn1wKPmFLfpcchu6eIozvWTcVPkfPPSqOwS7HyYlHUdMS+MSjKlmM9dBCh81kgxRWbXLkz0vf6dQ3QIDAQAB
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user_api.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.user_api.entrypoints=web"
      - "traefik.http.routers.user_api.priority=5"
    networks:
      - traefik_net
    command:
      - "sh"
      - "-c"
      - "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  user_db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - postgres_data_user_db:/var/lib/postgresql/data
    networks:
      - traefik_net

  blog_service:
    image: blog_service:latest
    volumes:
      - ../blog_api:/app
    container_name: blog_service
    ports:
      - "8004:8000"
    depends_on:
      - blog_db
      - elasticsearch
      - keycloak
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@blog_db:5432/blog_db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=paw_connect
      - KEYCLOAK_ADMIN_CLIENT_SECRET=wSVxDu1FL5SIbdDlqEpr9wohnB8bxYO7
      - KEYCLOAK_CLIENT_ID=chat-service
      - KEYCLOAK_CLIENT_SECRET=0T6BYixnHhjEdiv8vnMMKJDiiIqM5IJu
      - KEYCLOAK_CALLBACK_URI=http://localhost:3000/
      - KEYCLOAK_CLIIENT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3V7fKMuAO055R158iL18lehMdjFOZr1P7tmvrbQK3v/9hgbB6ROhOAmT1Aj+ml7rNMb+eMeJEPvDuE5sQm9hMUAU88bWC/pqWyCIegEEWEixeItUrBZLxEsmWagF5wFc90juNxu0qXEf2r/oKuRSdWuJXRx4IRkZm24XzlTLI/z7DZUvRL3t4e/XpnLgb8dVRw/xSmrqAFnbXbRaESDpp77KhTKlhxkVBiT5rBKRwAwI3a7kEYEFtvX3wpRimGPOh/uogtbHn1wKPmFLfpcchu6eIozvWTcVPkfPPSqOwS7HyYlHUdMS+MSjKlmM9dBCh81kgxRWbXLkz0vf6dQ3QIDAQAB
      - PYTHONUNBUFFERED=1
      - MINIO_HOST=minio:9000
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
      - MINIO_BUCKET=blog-media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog_api.rule=PathPrefix(`/api/blog`)"
      - "traefik.http.routers.blog_api.entrypoints=web"
      - "traefik.http.routers.blog_api.priority=5"
    networks:
      - traefik_net
    command:
      - "sh"
      - "-c"
      - "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  blog_db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data_blog_db:/var/lib/postgresql/data
    networks:
      - traefik_net


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - traefik_net

  grafana:
    image: grafana/grafana
    ports:
      - "3003:3000"
    networks:
      - traefik_net

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
        - traefik_net

networks:
  traefik_net:
    driver: bridge

volumes:
  keycloak_data:
  elasticsearch_data:
  postgres_data_chat_db:
  postgres_data_user_db:
  postgres_data_blog_db:
  node_modules:
  minio-data:
