global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:8000']
  - job_name: 'blog_service'
    static_configs:
      - targets: ['blog_service:8000']
  - job_name: 'channels_service'
    static_configs:
      - targets: ['channels_service:8000']
  - job_name: 'chat_service'
    static_configs:
      - targets: ['chat_service:8000']